# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created: Mon Nov 30 15:59:27 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_controlMontura(object):
    def setupUi(self, controlMontura):
        controlMontura.setObjectName(_fromUtf8("controlMontura"))
        controlMontura.resize(1036, 389)
        self.centralwidget = QtGui.QWidget(controlMontura)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(250, 30, 391, 291))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.mode = QtGui.QTabWidget(self.verticalLayoutWidget)
        self.mode.setObjectName(_fromUtf8("mode"))
        self.manualMode = QtGui.QWidget()
        self.manualMode.setObjectName(_fromUtf8("manualMode"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.manualMode)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 60, 101, 131))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lcdNumber = QtGui.QLCDNumber(self.horizontalLayoutWidget)
        self.lcdNumber.setNumDigits(2)
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.horizontalLayout.addWidget(self.lcdNumber)
        self.labelVelocidad = QtGui.QLabel(self.manualMode)
        self.labelVelocidad.setGeometry(QtCore.QRect(30, 30, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelVelocidad.setFont(font)
        self.labelVelocidad.setObjectName(_fromUtf8("labelVelocidad"))
        self.qLed_3_2 = QLed(self.manualMode)
        self.qLed_3_2.setGeometry(QtCore.QRect(180, 80, 25, 25))
        self.qLed_3_2.setProperty("value", False)
        self.qLed_3_2.setOnColour(QLed.Red)
        self.qLed_3_2.setOffColour(QLed.Grey)
        self.qLed_3_2.setShape(QLed.Circle)
        self.qLed_3_2.setObjectName(_fromUtf8("qLed_3_2"))
        self.qLed_3_3 = QLed(self.manualMode)
        self.qLed_3_3.setGeometry(QtCore.QRect(210, 80, 25, 25))
        self.qLed_3_3.setProperty("value", False)
        self.qLed_3_3.setOnColour(QLed.Red)
        self.qLed_3_3.setOffColour(QLed.Grey)
        self.qLed_3_3.setShape(QLed.Circle)
        self.qLed_3_3.setObjectName(_fromUtf8("qLed_3_3"))
        self.qLed_3_4 = QLed(self.manualMode)
        self.qLed_3_4.setGeometry(QtCore.QRect(240, 80, 25, 25))
        self.qLed_3_4.setProperty("value", False)
        self.qLed_3_4.setOnColour(QLed.Red)
        self.qLed_3_4.setOffColour(QLed.Grey)
        self.qLed_3_4.setShape(QLed.Circle)
        self.qLed_3_4.setObjectName(_fromUtf8("qLed_3_4"))
        self.qLed_3_5 = QLed(self.manualMode)
        self.qLed_3_5.setGeometry(QtCore.QRect(270, 80, 25, 25))
        self.qLed_3_5.setProperty("value", False)
        self.qLed_3_5.setOnColour(QLed.Red)
        self.qLed_3_5.setOffColour(QLed.Grey)
        self.qLed_3_5.setShape(QLed.Circle)
        self.qLed_3_5.setObjectName(_fromUtf8("qLed_3_5"))
        self.qLed_3_6 = QLed(self.manualMode)
        self.qLed_3_6.setGeometry(QtCore.QRect(300, 80, 25, 25))
        self.qLed_3_6.setProperty("value", False)
        self.qLed_3_6.setOnColour(QLed.Red)
        self.qLed_3_6.setOffColour(QLed.Grey)
        self.qLed_3_6.setShape(QLed.Circle)
        self.qLed_3_6.setObjectName(_fromUtf8("qLed_3_6"))
        self.qLed_4_2 = QLed(self.manualMode)
        self.qLed_4_2.setGeometry(QtCore.QRect(180, 110, 25, 25))
        self.qLed_4_2.setProperty("value", False)
        self.qLed_4_2.setOnColour(QLed.Red)
        self.qLed_4_2.setOffColour(QLed.Grey)
        self.qLed_4_2.setShape(QLed.Circle)
        self.qLed_4_2.setObjectName(_fromUtf8("qLed_4_2"))
        self.qLed_3_7 = QLed(self.manualMode)
        self.qLed_3_7.setGeometry(QtCore.QRect(330, 80, 25, 25))
        self.qLed_3_7.setProperty("value", False)
        self.qLed_3_7.setOnColour(QLed.Red)
        self.qLed_3_7.setOffColour(QLed.Grey)
        self.qLed_3_7.setShape(QLed.Circle)
        self.qLed_3_7.setObjectName(_fromUtf8("qLed_3_7"))
        self.qLed_3_1 = QLed(self.manualMode)
        self.qLed_3_1.setGeometry(QtCore.QRect(150, 80, 25, 25))
        self.qLed_3_1.setProperty("value", False)
        self.qLed_3_1.setOnColour(QLed.Red)
        self.qLed_3_1.setOffColour(QLed.Grey)
        self.qLed_3_1.setShape(QLed.Circle)
        self.qLed_3_1.setObjectName(_fromUtf8("qLed_3_1"))
        self.qLed_2_6 = QLed(self.manualMode)
        self.qLed_2_6.setGeometry(QtCore.QRect(300, 50, 25, 25))
        self.qLed_2_6.setProperty("value", False)
        self.qLed_2_6.setOnColour(QLed.Red)
        self.qLed_2_6.setOffColour(QLed.Grey)
        self.qLed_2_6.setShape(QLed.Circle)
        self.qLed_2_6.setObjectName(_fromUtf8("qLed_2_6"))
        self.qLed_5_1 = QLed(self.manualMode)
        self.qLed_5_1.setGeometry(QtCore.QRect(150, 140, 25, 25))
        self.qLed_5_1.setProperty("value", False)
        self.qLed_5_1.setOnColour(QLed.Red)
        self.qLed_5_1.setOffColour(QLed.Grey)
        self.qLed_5_1.setShape(QLed.Circle)
        self.qLed_5_1.setObjectName(_fromUtf8("qLed_5_1"))
        self.qLed_5_2 = QLed(self.manualMode)
        self.qLed_5_2.setGeometry(QtCore.QRect(180, 140, 25, 25))
        self.qLed_5_2.setProperty("value", False)
        self.qLed_5_2.setOnColour(QLed.Red)
        self.qLed_5_2.setOffColour(QLed.Grey)
        self.qLed_5_2.setShape(QLed.Circle)
        self.qLed_5_2.setObjectName(_fromUtf8("qLed_5_2"))
        self.qLed_5_4 = QLed(self.manualMode)
        self.qLed_5_4.setGeometry(QtCore.QRect(240, 140, 25, 25))
        self.qLed_5_4.setProperty("value", False)
        self.qLed_5_4.setOnColour(QLed.Red)
        self.qLed_5_4.setOffColour(QLed.Grey)
        self.qLed_5_4.setShape(QLed.Circle)
        self.qLed_5_4.setObjectName(_fromUtf8("qLed_5_4"))
        self.qLed_5_7 = QLed(self.manualMode)
        self.qLed_5_7.setGeometry(QtCore.QRect(300, 140, 25, 25))
        self.qLed_5_7.setProperty("value", False)
        self.qLed_5_7.setOnColour(QLed.Red)
        self.qLed_5_7.setOffColour(QLed.Grey)
        self.qLed_5_7.setShape(QLed.Circle)
        self.qLed_5_7.setObjectName(_fromUtf8("qLed_5_7"))
        self.qLed_5_3 = QLed(self.manualMode)
        self.qLed_5_3.setGeometry(QtCore.QRect(210, 140, 25, 25))
        self.qLed_5_3.setProperty("value", False)
        self.qLed_5_3.setOnColour(QLed.Red)
        self.qLed_5_3.setOffColour(QLed.Grey)
        self.qLed_5_3.setShape(QLed.Circle)
        self.qLed_5_3.setObjectName(_fromUtf8("qLed_5_3"))
        self.qLed_5_8 = QLed(self.manualMode)
        self.qLed_5_8.setGeometry(QtCore.QRect(330, 140, 25, 25))
        self.qLed_5_8.setProperty("value", False)
        self.qLed_5_8.setOnColour(QLed.Red)
        self.qLed_5_8.setOffColour(QLed.Grey)
        self.qLed_5_8.setShape(QLed.Circle)
        self.qLed_5_8.setObjectName(_fromUtf8("qLed_5_8"))
        self.qLed_5_6 = QLed(self.manualMode)
        self.qLed_5_6.setGeometry(QtCore.QRect(270, 140, 25, 25))
        self.qLed_5_6.setProperty("value", False)
        self.qLed_5_6.setOnColour(QLed.Red)
        self.qLed_5_6.setOffColour(QLed.Grey)
        self.qLed_5_6.setShape(QLed.Circle)
        self.qLed_5_6.setObjectName(_fromUtf8("qLed_5_6"))
        self.qLed_4_3 = QLed(self.manualMode)
        self.qLed_4_3.setGeometry(QtCore.QRect(210, 110, 25, 25))
        self.qLed_4_3.setProperty("value", False)
        self.qLed_4_3.setOnColour(QLed.Red)
        self.qLed_4_3.setOffColour(QLed.Grey)
        self.qLed_4_3.setShape(QLed.Circle)
        self.qLed_4_3.setObjectName(_fromUtf8("qLed_4_3"))
        self.qLed_4_4 = QLed(self.manualMode)
        self.qLed_4_4.setGeometry(QtCore.QRect(240, 110, 25, 25))
        self.qLed_4_4.setProperty("value", False)
        self.qLed_4_4.setOnColour(QLed.Red)
        self.qLed_4_4.setOffColour(QLed.Grey)
        self.qLed_4_4.setShape(QLed.Circle)
        self.qLed_4_4.setObjectName(_fromUtf8("qLed_4_4"))
        self.qLed_4_5 = QLed(self.manualMode)
        self.qLed_4_5.setGeometry(QtCore.QRect(270, 110, 25, 25))
        self.qLed_4_5.setProperty("value", False)
        self.qLed_4_5.setOnColour(QLed.Red)
        self.qLed_4_5.setOffColour(QLed.Grey)
        self.qLed_4_5.setShape(QLed.Circle)
        self.qLed_4_5.setObjectName(_fromUtf8("qLed_4_5"))
        self.qLed_4_6 = QLed(self.manualMode)
        self.qLed_4_6.setGeometry(QtCore.QRect(300, 110, 25, 25))
        self.qLed_4_6.setProperty("value", False)
        self.qLed_4_6.setOnColour(QLed.Red)
        self.qLed_4_6.setOffColour(QLed.Grey)
        self.qLed_4_6.setShape(QLed.Circle)
        self.qLed_4_6.setObjectName(_fromUtf8("qLed_4_6"))
        self.qLed_4_7 = QLed(self.manualMode)
        self.qLed_4_7.setGeometry(QtCore.QRect(330, 110, 25, 25))
        self.qLed_4_7.setProperty("value", False)
        self.qLed_4_7.setOnColour(QLed.Red)
        self.qLed_4_7.setOffColour(QLed.Grey)
        self.qLed_4_7.setShape(QLed.Circle)
        self.qLed_4_7.setObjectName(_fromUtf8("qLed_4_7"))
        self.qLed_4_1 = QLed(self.manualMode)
        self.qLed_4_1.setGeometry(QtCore.QRect(150, 110, 25, 25))
        self.qLed_4_1.setProperty("value", False)
        self.qLed_4_1.setOnColour(QLed.Red)
        self.qLed_4_1.setOffColour(QLed.Grey)
        self.qLed_4_1.setShape(QLed.Circle)
        self.qLed_4_1.setObjectName(_fromUtf8("qLed_4_1"))
        self.qLed_6_3 = QLed(self.manualMode)
        self.qLed_6_3.setGeometry(QtCore.QRect(210, 170, 25, 25))
        self.qLed_6_3.setProperty("value", False)
        self.qLed_6_3.setOnColour(QLed.Red)
        self.qLed_6_3.setOffColour(QLed.Grey)
        self.qLed_6_3.setShape(QLed.Circle)
        self.qLed_6_3.setObjectName(_fromUtf8("qLed_6_3"))
        self.qLed_2_3 = QLed(self.manualMode)
        self.qLed_2_3.setGeometry(QtCore.QRect(210, 50, 25, 25))
        self.qLed_2_3.setProperty("value", False)
        self.qLed_2_3.setOnColour(QLed.Red)
        self.qLed_2_3.setOffColour(QLed.Grey)
        self.qLed_2_3.setShape(QLed.Circle)
        self.qLed_2_3.setObjectName(_fromUtf8("qLed_2_3"))
        self.qLed_2_2 = QLed(self.manualMode)
        self.qLed_2_2.setGeometry(QtCore.QRect(180, 50, 25, 25))
        self.qLed_2_2.setProperty("value", False)
        self.qLed_2_2.setOnColour(QLed.Red)
        self.qLed_2_2.setOffColour(QLed.Grey)
        self.qLed_2_2.setShape(QLed.Circle)
        self.qLed_2_2.setObjectName(_fromUtf8("qLed_2_2"))
        self.qLed_2_1 = QLed(self.manualMode)
        self.qLed_2_1.setGeometry(QtCore.QRect(150, 50, 25, 25))
        self.qLed_2_1.setProperty("value", False)
        self.qLed_2_1.setOnColour(QLed.Red)
        self.qLed_2_1.setOffColour(QLed.Grey)
        self.qLed_2_1.setShape(QLed.Circle)
        self.qLed_2_1.setObjectName(_fromUtf8("qLed_2_1"))
        self.qLed_6_4 = QLed(self.manualMode)
        self.qLed_6_4.setGeometry(QtCore.QRect(240, 170, 25, 25))
        self.qLed_6_4.setProperty("value", False)
        self.qLed_6_4.setOnColour(QLed.Red)
        self.qLed_6_4.setOffColour(QLed.Grey)
        self.qLed_6_4.setShape(QLed.Circle)
        self.qLed_6_4.setObjectName(_fromUtf8("qLed_6_4"))
        self.qLed_6_5 = QLed(self.manualMode)
        self.qLed_6_5.setGeometry(QtCore.QRect(270, 170, 25, 25))
        self.qLed_6_5.setProperty("value", False)
        self.qLed_6_5.setOnColour(QLed.Red)
        self.qLed_6_5.setOffColour(QLed.Grey)
        self.qLed_6_5.setShape(QLed.Circle)
        self.qLed_6_5.setObjectName(_fromUtf8("qLed_6_5"))
        self.qLed_6_7 = QLed(self.manualMode)
        self.qLed_6_7.setGeometry(QtCore.QRect(330, 170, 25, 25))
        self.qLed_6_7.setProperty("value", False)
        self.qLed_6_7.setOnColour(QLed.Red)
        self.qLed_6_7.setOffColour(QLed.Grey)
        self.qLed_6_7.setShape(QLed.Circle)
        self.qLed_6_7.setObjectName(_fromUtf8("qLed_6_7"))
        self.qLed_6_6 = QLed(self.manualMode)
        self.qLed_6_6.setGeometry(QtCore.QRect(300, 170, 25, 25))
        self.qLed_6_6.setProperty("value", False)
        self.qLed_6_6.setOnColour(QLed.Red)
        self.qLed_6_6.setOffColour(QLed.Grey)
        self.qLed_6_6.setShape(QLed.Circle)
        self.qLed_6_6.setObjectName(_fromUtf8("qLed_6_6"))
        self.qLed_6_2 = QLed(self.manualMode)
        self.qLed_6_2.setGeometry(QtCore.QRect(180, 170, 25, 25))
        self.qLed_6_2.setProperty("value", False)
        self.qLed_6_2.setOnColour(QLed.Red)
        self.qLed_6_2.setOffColour(QLed.Grey)
        self.qLed_6_2.setShape(QLed.Circle)
        self.qLed_6_2.setObjectName(_fromUtf8("qLed_6_2"))
        self.qLed_6_1 = QLed(self.manualMode)
        self.qLed_6_1.setGeometry(QtCore.QRect(150, 170, 25, 25))
        self.qLed_6_1.setProperty("value", False)
        self.qLed_6_1.setOnColour(QLed.Red)
        self.qLed_6_1.setOffColour(QLed.Grey)
        self.qLed_6_1.setShape(QLed.Circle)
        self.qLed_6_1.setObjectName(_fromUtf8("qLed_6_1"))
        self.qLed_7_7 = QLed(self.manualMode)
        self.qLed_7_7.setGeometry(QtCore.QRect(330, 200, 25, 25))
        self.qLed_7_7.setProperty("value", False)
        self.qLed_7_7.setOnColour(QLed.Red)
        self.qLed_7_7.setOffColour(QLed.Grey)
        self.qLed_7_7.setShape(QLed.Circle)
        self.qLed_7_7.setObjectName(_fromUtf8("qLed_7_7"))
        self.qLed_7_6 = QLed(self.manualMode)
        self.qLed_7_6.setGeometry(QtCore.QRect(300, 200, 25, 25))
        self.qLed_7_6.setProperty("value", False)
        self.qLed_7_6.setOnColour(QLed.Red)
        self.qLed_7_6.setOffColour(QLed.Grey)
        self.qLed_7_6.setShape(QLed.Circle)
        self.qLed_7_6.setObjectName(_fromUtf8("qLed_7_6"))
        self.qLed_7_1 = QLed(self.manualMode)
        self.qLed_7_1.setGeometry(QtCore.QRect(150, 200, 25, 25))
        self.qLed_7_1.setProperty("value", False)
        self.qLed_7_1.setOnColour(QLed.Red)
        self.qLed_7_1.setOffColour(QLed.Grey)
        self.qLed_7_1.setShape(QLed.Circle)
        self.qLed_7_1.setObjectName(_fromUtf8("qLed_7_1"))
        self.qLed_7_5 = QLed(self.manualMode)
        self.qLed_7_5.setGeometry(QtCore.QRect(270, 200, 25, 25))
        self.qLed_7_5.setProperty("value", False)
        self.qLed_7_5.setOnColour(QLed.Red)
        self.qLed_7_5.setOffColour(QLed.Grey)
        self.qLed_7_5.setShape(QLed.Circle)
        self.qLed_7_5.setObjectName(_fromUtf8("qLed_7_5"))
        self.qLed_7_4 = QLed(self.manualMode)
        self.qLed_7_4.setGeometry(QtCore.QRect(240, 200, 25, 25))
        self.qLed_7_4.setProperty("value", False)
        self.qLed_7_4.setOnColour(QLed.Red)
        self.qLed_7_4.setOffColour(QLed.Grey)
        self.qLed_7_4.setShape(QLed.Circle)
        self.qLed_7_4.setObjectName(_fromUtf8("qLed_7_4"))
        self.qLed_7_3 = QLed(self.manualMode)
        self.qLed_7_3.setGeometry(QtCore.QRect(210, 200, 25, 25))
        self.qLed_7_3.setProperty("value", False)
        self.qLed_7_3.setOnColour(QLed.Red)
        self.qLed_7_3.setOffColour(QLed.Grey)
        self.qLed_7_3.setShape(QLed.Circle)
        self.qLed_7_3.setObjectName(_fromUtf8("qLed_7_3"))
        self.qLed_7_2 = QLed(self.manualMode)
        self.qLed_7_2.setGeometry(QtCore.QRect(180, 200, 25, 25))
        self.qLed_7_2.setProperty("value", False)
        self.qLed_7_2.setOnColour(QLed.Red)
        self.qLed_7_2.setOffColour(QLed.Grey)
        self.qLed_7_2.setShape(QLed.Circle)
        self.qLed_7_2.setObjectName(_fromUtf8("qLed_7_2"))
        self.qLed_2_4 = QLed(self.manualMode)
        self.qLed_2_4.setGeometry(QtCore.QRect(240, 50, 25, 25))
        self.qLed_2_4.setProperty("value", False)
        self.qLed_2_4.setOnColour(QLed.Red)
        self.qLed_2_4.setOffColour(QLed.Grey)
        self.qLed_2_4.setShape(QLed.Circle)
        self.qLed_2_4.setObjectName(_fromUtf8("qLed_2_4"))
        self.qLed_2_5 = QLed(self.manualMode)
        self.qLed_2_5.setGeometry(QtCore.QRect(270, 50, 25, 25))
        self.qLed_2_5.setProperty("value", False)
        self.qLed_2_5.setOnColour(QLed.Red)
        self.qLed_2_5.setOffColour(QLed.Grey)
        self.qLed_2_5.setShape(QLed.Circle)
        self.qLed_2_5.setObjectName(_fromUtf8("qLed_2_5"))
        self.qLed_1_1 = QLed(self.manualMode)
        self.qLed_1_1.setGeometry(QtCore.QRect(150, 20, 25, 25))
        self.qLed_1_1.setProperty("value", False)
        self.qLed_1_1.setOnColour(QLed.Red)
        self.qLed_1_1.setOffColour(QLed.Grey)
        self.qLed_1_1.setShape(QLed.Circle)
        self.qLed_1_1.setObjectName(_fromUtf8("qLed_1_1"))
        self.qLed_1_2 = QLed(self.manualMode)
        self.qLed_1_2.setGeometry(QtCore.QRect(180, 20, 25, 25))
        self.qLed_1_2.setProperty("value", False)
        self.qLed_1_2.setOnColour(QLed.Red)
        self.qLed_1_2.setOffColour(QLed.Grey)
        self.qLed_1_2.setShape(QLed.Circle)
        self.qLed_1_2.setObjectName(_fromUtf8("qLed_1_2"))
        self.qLed_2_7 = QLed(self.manualMode)
        self.qLed_2_7.setGeometry(QtCore.QRect(330, 50, 25, 25))
        self.qLed_2_7.setProperty("value", False)
        self.qLed_2_7.setOnColour(QLed.Red)
        self.qLed_2_7.setOffColour(QLed.Grey)
        self.qLed_2_7.setShape(QLed.Circle)
        self.qLed_2_7.setObjectName(_fromUtf8("qLed_2_7"))
        self.qLed_1_7 = QLed(self.manualMode)
        self.qLed_1_7.setGeometry(QtCore.QRect(330, 20, 25, 25))
        self.qLed_1_7.setProperty("value", False)
        self.qLed_1_7.setOnColour(QLed.Red)
        self.qLed_1_7.setOffColour(QLed.Grey)
        self.qLed_1_7.setShape(QLed.Circle)
        self.qLed_1_7.setObjectName(_fromUtf8("qLed_1_7"))
        self.qLed_1_4 = QLed(self.manualMode)
        self.qLed_1_4.setGeometry(QtCore.QRect(240, 20, 25, 25))
        self.qLed_1_4.setProperty("value", False)
        self.qLed_1_4.setOnColour(QLed.Red)
        self.qLed_1_4.setOffColour(QLed.Grey)
        self.qLed_1_4.setShape(QLed.Circle)
        self.qLed_1_4.setObjectName(_fromUtf8("qLed_1_4"))
        self.qLed_1_3 = QLed(self.manualMode)
        self.qLed_1_3.setGeometry(QtCore.QRect(210, 20, 25, 25))
        self.qLed_1_3.setProperty("value", False)
        self.qLed_1_3.setOnColour(QLed.Red)
        self.qLed_1_3.setOffColour(QLed.Grey)
        self.qLed_1_3.setShape(QLed.Circle)
        self.qLed_1_3.setObjectName(_fromUtf8("qLed_1_3"))
        self.qLed_1_6 = QLed(self.manualMode)
        self.qLed_1_6.setGeometry(QtCore.QRect(300, 20, 25, 25))
        self.qLed_1_6.setProperty("value", False)
        self.qLed_1_6.setOnColour(QLed.Red)
        self.qLed_1_6.setOffColour(QLed.Grey)
        self.qLed_1_6.setShape(QLed.Circle)
        self.qLed_1_6.setObjectName(_fromUtf8("qLed_1_6"))
        self.qLed_1_5 = QLed(self.manualMode)
        self.qLed_1_5.setGeometry(QtCore.QRect(270, 20, 25, 25))
        self.qLed_1_5.setProperty("value", False)
        self.qLed_1_5.setOnColour(QLed.Red)
        self.qLed_1_5.setOffColour(QLed.Grey)
        self.qLed_1_5.setShape(QLed.Circle)
        self.qLed_1_5.setObjectName(_fromUtf8("qLed_1_5"))
        self.mode.addTab(self.manualMode, _fromUtf8(""))
        self.automaticMode = QtGui.QWidget()
        self.automaticMode.setObjectName(_fromUtf8("automaticMode"))
        self.verticalLayoutWidget_6 = QtGui.QWidget(self.automaticMode)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(10, 10, 171, 141))
        self.verticalLayoutWidget_6.setObjectName(_fromUtf8("verticalLayoutWidget_6"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.modoAuto = QtGui.QFrame(self.verticalLayoutWidget_6)
        self.modoAuto.setFrameShape(QtGui.QFrame.StyledPanel)
        self.modoAuto.setFrameShadow(QtGui.QFrame.Raised)
        self.modoAuto.setObjectName(_fromUtf8("modoAuto"))
        self.groupBox = QtGui.QGroupBox(self.modoAuto)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 171, 81))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.checkBox = QtGui.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(10, 20, 131, 22))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("aim.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox.setIcon(icon)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.checkBox_2 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 40, 141, 22))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("track.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_2.setIcon(icon1)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.checkBox_3 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 60, 97, 22))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("sweep.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_3.setIcon(icon2)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.pushButton = QtGui.QPushButton(self.modoAuto)
        self.pushButton.setGeometry(QtCore.QRect(10, 100, 71, 27))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_3 = QtGui.QPushButton(self.modoAuto)
        self.pushButton_3.setGeometry(QtCore.QRect(90, 100, 71, 27))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.verticalLayout_6.addWidget(self.modoAuto)
        self.verticalLayoutWidget_7 = QtGui.QWidget(self.automaticMode)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(189, 10, 191, 181))
        self.verticalLayoutWidget_7.setObjectName(_fromUtf8("verticalLayoutWidget_7"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.frame = QtGui.QFrame(self.verticalLayoutWidget_7)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(40, 30, 111, 17))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(40, 80, 111, 17))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.azVentana = QtGui.QTextEdit(self.frame)
        self.azVentana.setGeometry(QtCore.QRect(10, 50, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.azVentana.setFont(font)
        self.azVentana.setObjectName(_fromUtf8("azVentana"))
        self.elVentana = QtGui.QTextEdit(self.frame)
        self.elVentana.setGeometry(QtCore.QRect(100, 50, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.elVentana.setFont(font)
        self.elVentana.setObjectName(_fromUtf8("elVentana"))
        self.label_13 = QtGui.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(70, 60, 31, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.azPaso = QtGui.QTextEdit(self.frame)
        self.azPaso.setGeometry(QtCore.QRect(10, 100, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.azPaso.setFont(font)
        self.azPaso.setObjectName(_fromUtf8("azPaso"))
        self.elPaso = QtGui.QTextEdit(self.frame)
        self.elPaso.setGeometry(QtCore.QRect(100, 100, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.elPaso.setFont(font)
        self.elPaso.setObjectName(_fromUtf8("elPaso"))
        self.label_15 = QtGui.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(70, 110, 31, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.frame)
        self.label_16.setGeometry(QtCore.QRect(160, 110, 21, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_12 = QtGui.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(10, 150, 111, 17))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.tiempoBarrido = QtGui.QTextEdit(self.frame)
        self.tiempoBarrido.setGeometry(QtCore.QRect(120, 140, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tiempoBarrido.setFont(font)
        self.tiempoBarrido.setObjectName(_fromUtf8("tiempoBarrido"))
        self.label_20 = QtGui.QLabel(self.frame)
        self.label_20.setGeometry(QtCore.QRect(170, 150, 16, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.frame)
        self.label_21.setGeometry(QtCore.QRect(160, 60, 31, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout_7.addWidget(self.frame)
        self.textEdit_11 = QtGui.QTextEdit(self.automaticMode)
        self.textEdit_11.setGeometry(QtCore.QRect(10, 200, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_11.setFont(font)
        self.textEdit_11.setObjectName(_fromUtf8("textEdit_11"))
        self.textEdit_12 = QtGui.QTextEdit(self.automaticMode)
        self.textEdit_12.setGeometry(QtCore.QRect(200, 200, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_12.setFont(font)
        self.textEdit_12.setObjectName(_fromUtf8("textEdit_12"))
        self.label_17 = QtGui.QLabel(self.automaticMode)
        self.label_17.setGeometry(QtCore.QRect(150, 210, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.automaticMode)
        self.label_18.setGeometry(QtCore.QRect(340, 210, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.automaticMode)
        self.label_19.setGeometry(QtCore.QRect(10, 170, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.mode.addTab(self.automaticMode, _fromUtf8(""))
        self.verticalLayout.addWidget(self.mode)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 40, 151, 51))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.textEdit_2 = QtGui.QTextEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setObjectName(_fromUtf8("textEdit_2"))
        self.verticalLayout_2.addWidget(self.textEdit_2)
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 100, 151, 51))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.textEdit_3 = QtGui.QTextEdit(self.verticalLayoutWidget_3)
        self.textEdit_3.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.textEdit_3.setFont(font)
        self.textEdit_3.setObjectName(_fromUtf8("textEdit_3"))
        self.verticalLayout_3.addWidget(self.textEdit_3)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(200, 50, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(200, 110, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(20, 190, 151, 51))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.textEdit = QtGui.QTextEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout_4.addWidget(self.textEdit)
        self.verticalLayoutWidget_5 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(20, 250, 151, 51))
        self.verticalLayoutWidget_5.setObjectName(_fromUtf8("verticalLayoutWidget_5"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.textEdit_4 = QtGui.QTextEdit(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.textEdit_4.setFont(font)
        self.textEdit_4.setObjectName(_fromUtf8("textEdit_4"))
        self.verticalLayout_5.addWidget(self.textEdit_4)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 160, 151, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(180, 260, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(180, 200, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.toolButton = QtGui.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(20, 310, 31, 31))
        self.toolButton.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("home.jpeg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon3)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.toolButton_2 = QtGui.QToolButton(self.centralwidget)
        self.toolButton_2.setGeometry(QtCore.QRect(100, 310, 31, 31))
        self.toolButton_2.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("send.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon4)
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.toolButton_3 = QtGui.QToolButton(self.centralwidget)
        self.toolButton_3.setGeometry(QtCore.QRect(60, 310, 31, 31))
        self.toolButton_3.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("unlock.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon5)
        self.toolButton_3.setObjectName(_fromUtf8("toolButton_3"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(180, 50, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(180, 110, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(650, 10, 111, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayoutWidget_8 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(650, 30, 371, 301))
        self.verticalLayoutWidget_8.setObjectName(_fromUtf8("verticalLayoutWidget_8"))
        self.plotADC = QtGui.QVBoxLayout(self.verticalLayoutWidget_8)
        self.plotADC.setMargin(0)
        self.plotADC.setObjectName(_fromUtf8("plotADC"))
        self.toolButton_4 = QtGui.QToolButton(self.centralwidget)
        self.toolButton_4.setGeometry(QtCore.QRect(140, 310, 31, 31))
        self.toolButton_4.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("compas.jpeg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_4.setIcon(icon6)
        self.toolButton_4.setObjectName(_fromUtf8("toolButton_4"))
        controlMontura.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(controlMontura)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1036, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuAcerca_de = QtGui.QMenu(self.menubar)
        self.menuAcerca_de.setObjectName(_fromUtf8("menuAcerca_de"))
        controlMontura.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(controlMontura)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        controlMontura.setStatusBar(self.statusbar)
        self.actionBuscar_GPS = QtGui.QAction(controlMontura)
        self.actionBuscar_GPS.setObjectName(_fromUtf8("actionBuscar_GPS"))
        self.actionManual = QtGui.QAction(controlMontura)
        self.actionManual.setObjectName(_fromUtf8("actionManual"))
        self.actionSalr = QtGui.QAction(controlMontura)
        self.actionSalr.setEnabled(True)
        self.actionSalr.setIconVisibleInMenu(True)
        self.actionSalr.setObjectName(_fromUtf8("actionSalr"))
        self.actionAbrir_Stellarium = QtGui.QAction(controlMontura)
        self.actionAbrir_Stellarium.setObjectName(_fromUtf8("actionAbrir_Stellarium"))
        self.actionAcerca = QtGui.QAction(controlMontura)
        self.actionAcerca.setObjectName(_fromUtf8("actionAcerca"))
        self.menuFile.addAction(self.actionAbrir_Stellarium)
        self.menuFile.addAction(self.actionSalr)
        self.menuEdit.addAction(self.actionManual)
        self.menuAcerca_de.addAction(self.actionAcerca)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuAcerca_de.menuAction())

        self.retranslateUi(controlMontura)
        self.mode.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(controlMontura)

    def retranslateUi(self, controlMontura):
        controlMontura.setWindowTitle(_translate("controlMontura", "Control RT", None))
        self.labelVelocidad.setText(_translate("controlMontura", "Velocidad ", None))
        self.qLed_3_2.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_3_2.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_3_3.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_3_3.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_3_4.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_3_4.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_3_5.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_3_5.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_3_6.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_3_6.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_4_2.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_4_2.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_3_7.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_3_7.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_3_1.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_3_1.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_2_6.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_2_6.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_5_1.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_5_1.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_5_2.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_5_2.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_5_4.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_5_4.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_5_7.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_5_7.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_5_3.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_5_3.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_5_8.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_5_8.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_5_6.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_5_6.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_4_3.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_4_3.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_4_4.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_4_4.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_4_5.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_4_5.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_4_6.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_4_6.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_4_7.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_4_7.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_4_1.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_4_1.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_6_3.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_6_3.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_2_3.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_2_3.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_2_2.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_2_2.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_2_1.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_2_1.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_6_4.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_6_4.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_6_5.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_6_5.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_6_7.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_6_7.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_6_6.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_6_6.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_6_2.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_6_2.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_6_1.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_6_1.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_7_7.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_7_7.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_7_6.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_7_6.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_7_1.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_7_1.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_7_5.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_7_5.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_7_4.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_7_4.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_7_3.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_7_3.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_7_2.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_7_2.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_2_4.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_2_4.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_2_5.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_2_5.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_1_1.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_1_1.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_1_2.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_1_2.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_2_7.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_2_7.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_1_7.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_1_7.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_1_4.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_1_4.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_1_3.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_1_3.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_1_6.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_1_6.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.qLed_1_5.setToolTip(_translate("controlMontura", "Binary Led", None))
        self.qLed_1_5.setWhatsThis(_translate("controlMontura", "Led widget", None))
        self.mode.setTabText(self.mode.indexOf(self.manualMode), _translate("controlMontura", "Manual", None))
        self.groupBox.setTitle(_translate("controlMontura", "Modo", None))
        self.checkBox.setText(_translate("controlMontura", "Localización", None))
        self.checkBox_2.setText(_translate("controlMontura", "Seguimiento", None))
        self.checkBox_3.setText(_translate("controlMontura", "Barrido", None))
        self.pushButton.setText(_translate("controlMontura", "Iniciar", None))
        self.pushButton_3.setText(_translate("controlMontura", "Detener", None))
        self.label_8.setText(_translate("controlMontura", "Tamaño Ventana", None))
        self.label_9.setText(_translate("controlMontura", "Paso de Ventana", None))
        self.azVentana.setHtml(_translate("controlMontura", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.elVentana.setHtml(_translate("controlMontura", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.label_13.setText(_translate("controlMontura", "°AZ", None))
        self.azPaso.setHtml(_translate("controlMontura", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.elPaso.setHtml(_translate("controlMontura", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.label_15.setText(_translate("controlMontura", "°AZ", None))
        self.label_16.setText(_translate("controlMontura", "°EL", None))
        self.label_12.setText(_translate("controlMontura", "Tiempo ventana", None))
        self.tiempoBarrido.setHtml(_translate("controlMontura", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.label_20.setText(_translate("controlMontura", "s", None))
        self.label_21.setText(_translate("controlMontura", "°EL", None))
        self.textEdit_11.setHtml(_translate("controlMontura", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Not Obj</p></body></html>", None))
        self.textEdit_12.setHtml(_translate("controlMontura", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Not Obj</p></body></html>", None))
        self.label_17.setText(_translate("controlMontura", "°AZ", None))
        self.label_18.setText(_translate("controlMontura", "°EL", None))
        self.label_19.setText(_translate("controlMontura", "Posición Objetivo", None))
        self.mode.setTabText(self.mode.indexOf(self.automaticMode), _translate("controlMontura", "Automático", None))
        self.textEdit_2.setHtml(_translate("controlMontura", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0.0000000</p></body></html>", None))
        self.textEdit_3.setHtml(_translate("controlMontura", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0.0000000</p></body></html>", None))
        self.label_2.setText(_translate("controlMontura", "Posición Geográfica", None))
        self.label_3.setText(_translate("controlMontura", "N", None))
        self.label_4.setText(_translate("controlMontura", "E", None))
        self.textEdit.setHtml(_translate("controlMontura", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0.0000000</p></body></html>", None))
        self.textEdit_4.setHtml(_translate("controlMontura", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0.0000000</p></body></html>", None))
        self.label_5.setText(_translate("controlMontura", "Posición Antena", None))
        self.label_6.setText(_translate("controlMontura", "°EL", None))
        self.label_7.setText(_translate("controlMontura", "°AZ", None))
        self.label_10.setText(_translate("controlMontura", "°", None))
        self.label_11.setText(_translate("controlMontura", "°", None))
        self.label.setText(_translate("controlMontura", "Señal recepetor", None))
        self.menuFile.setTitle(_translate("controlMontura", "Archivo", None))
        self.menuEdit.setTitle(_translate("controlMontura", "Posicionamiento", None))
        self.menuAcerca_de.setTitle(_translate("controlMontura", "Ayuda", None))
        self.actionBuscar_GPS.setText(_translate("controlMontura", "GPS", None))
        self.actionManual.setText(_translate("controlMontura", "Manual", None))
        self.actionSalr.setText(_translate("controlMontura", "Salir", None))
        self.actionAbrir_Stellarium.setText(_translate("controlMontura", "Abrir Stellarium", None))
        self.actionAcerca.setText(_translate("controlMontura", "Acerca", None))

from qled import QLed
